spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/productdb
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    database: PostgreSQL
    show-sql: true
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQLDialect


server:
  port: 8081
