spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/productdb
    username: ecommerce
    password: ecommerce
  jpa:
    database: PostgreSQL
    show-sql: true
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQLDialect


server:
  port: 8081
