spring:
  mongodb:
    uri: mongodb://localhost:27017/userdb
    database: userdb
  rabbitmq:
    host: localhost
    username: guest
    password: guest
    port: 5672

management:
  endpoints:
    web:
      exposure:
        include: "busrefresh"

server:
  port: 8082

eureka:
  client:
    server-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true

logging:
  file:
    name: logs/${spring.application.name}.log
  logback:
    rollingpolicy:
      max-file-size: 5MB
      max-history: 7
