spring:
  mongodb:
    uri: mongodb://localhost:27017/userdb
    database: userdb
  rabbitmq:
    host: localhost
    username: guest
    password: guest
    port: 5672

management:
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans


server:
  port: 8082

eureka:
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.2
    hostname: localhost
  client:
    server-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true

logging:
  file:
    name: logs/${spring.application.name}.log
  logback:
    rollingpolicy:
      max-file-size: 5MB
      max-history: 7
